robot:
    path: /
    defaults: { _controller: "ErikaBundle:Robot:index" }

robot-search-movie:
    path: search/movie/{movie_name}
    defaults: { _controller: "ErikaBundle:Robot:searchMovie" }

robot-save-movie:
    path: save/movie/
    defaults: { _controller: "ErikaBundle:Robot:saveMovie" }

robot-search-serie:
    path: search/serie/{serie_name}
    defaults: {_controller: "ErikaBundle:Robot:searchSerie" }

robot-save-serie:
    path: save/serie/
    defaults: {_controller: "ErikaBundle:Robot:saveSerie"}

robot-search-serie-season:
    path: search/serie/season/
    defaults: {_controller: "ErikaBundle:Robot:searchSeason"}

robot-save-serie-season:
    path: save/serie/season/
    defaults: {_controller: "ErikaBundle:Robot:saveSeason"}