StreamingProducao:
    type: entity
    table: Streaming_Producao
    indexes:
        STR_ID:
            columns:
                - STR_ID
        PRD_ID:
            columns:
                - PRD_ID
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    manyToOne:
        str:
            targetEntity: Streaming
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                STR_ID:
                    referencedColumnName: ID
            orphanRemoval: false
        prd:
            targetEntity: Producao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PRD_ID:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
