ErikaBundle\Entity\ElencoProducaoTipo:
    type: entity
    table: Elenco_Producao_Tipo
    indexes:
        PRD_ID:
            columns:
                - PRD_ID
        TIPO_ELC_ID:
            columns:
                - TIPO_ELC_ID
        ELC_ID:
            columns:
                - ELC_ID
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    manyToOne:
        prd:
            targetEntity: Producao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PRD_ID:
                    referencedColumnName: ID
            orphanRemoval: false
        tipoElc:
            targetEntity: TipoElenco
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                TIPO_ELC_ID:
                    referencedColumnName: ID
            orphanRemoval: false
        elc:
            targetEntity: Elenco
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ELC_ID:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
