erika_homepage:
    path:     /
    defaults: { _controller: ErikaBundle:Default:index }

erika_robot:
    resource: "@ErikaBundle/Resources/config/routing/robot.yml"
    prefix:   /robot

erika_core:
    resource: "@ErikaBundle/Resources/config/routing/core.yml"
    prefix:   /core

erika_get_movie:
    path:     movie/{id_movie}
    defaults: { _controller: ErikaBundle:Api:GetMovie }
    methods:    [GET]

erika_put_movie:
    path:     movie/{id_movie}
    defaults: { _controller: ErikaBundle:Api:PutMovie }
    methods:  [PUT]

erika_post_visto:
    path:   visto/{id_producao}
    defaults: { _controller: ErikaBundle:Api:PutVisto }
    methods:  [POST]

erika_post_wishlist:
    path:     wishlist/{id_producao}
    defaults: { _controller: ErikaBundle:Api:postWishlist }
    methods:  [POST]

erika_get_serie:
    path:     serie/{id_serie}
    defaults: { _controller: ErikaBundle:Api:getSerie }
    methods:  [GET]

erika_get_serie_season:
    path:     serie/{id_serie}/season/{season}
    defaults: { _controller: ErikaBundle:Api:getSerieSeason }
    methods:  [GET]

erika_put_serie_episode_visto:
    path:     visto/episode/{id_episode}
    defaults: { _controller: ErikaBundle:Api:postEpisodeWatched }
    methods:  [PUT]

erika_put_serie_season_visto:
    path:     visto/serie/{id_serie}/season/{season}
    defaults: { _controller: ErikaBundle:Api:putSeasonVisto }
    methods:  [PUT]