erika_homepage:
    path:     /
    defaults: { _controller: ErikaBundle:Default:index }

erika_robot:
    resource: "@ErikaBundle/Resources/config/routing/robot.yml"
    prefix:   /robot

erika_core:
    resource: "@ErikaBundle/Resources/config/routing/core.yml"
    prefix:   /core

erika_movie:
    path:     movie/{id_movie}
    defaults: { _controller: ErikaBundle:Api:Movie }