services:
   erika.producao:
       class: ErikaBundle\Service\ProducaoService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.mcurl:
     class: ErikaBundle\Service\MCurl
   erika.genero:
       class: ErikaBundle\Service\GeneroService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.produtora:
       class: ErikaBundle\Service\ProdutoraService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.elenco:
       class: ErikaBundle\Service\ElencoService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.elenco_prducao_tipo:
       class: ErikaBundle\Service\ElencoProducaoTipoService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.genero_producao:
       class: ErikaBundle\Service\GeneroProducaoService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.produtora_producao:
       class: ErikaBundle\Service\ProdutoraProducaoService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.tipo_elenco:
       class: ErikaBundle\Service\TipoElencoService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.episodio:
       class: ErikaBundle\Service\EpisodioService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.elenco_episodio_tipo:
       class: ErikaBundle\Service\ElencoEpisodioTipoService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.watched:
       class: ErikaBundle\Service\WatchedService
       arguments: ['@doctrine.orm.entity_manager', "@service_container"]
   erika.wishlist:
       class: ErikaBundle\Service\WishlistService
       arguments: ['@doctrine.orm.entity_manager', "@service_container"]