services:
   erika.producao:
       class: ErikaBundle\Service\ProducaoService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.mcurl:
     class: ErikaBundle\Service\MCurl
   erika.genero:
       class: ErikaBundle\Service\GeneroService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.produtora:
       class: ErikaBundle\Service\ProdutoraService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]
   erika.elenco:
       class: ErikaBundle\Service\ElencoService
       arguments: ["@doctrine.orm.entity_manager", "@service_container"]